trigger:
  branches:
    include:
      - main

pool:
  name: Default  # your self‑hosted agent pool

variables:
  buildConfiguration: "Release"

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"

          - script: |
              cd backend
              npm install
              npm run lint || echo "No lint errors"
            displayName: "Backend: Install & Lint"

          - script: |
              cd backend
              npm run build || exit 0
            displayName: "Backend: Build (optional)"

          - script: |
              cd frontend
              npm install
              npm run lint || echo "No lint errors"
            displayName: "Frontend: Install & Lint"

          - script: |
              cd frontend
              npm run build
            displayName: "Frontend: Build"

  - stage: Test
    jobs:
      - job: TestJob
        steps:
          - script: |
              echo "No tests to run"
            displayName: "Run Tests"

  - stage: Deliver
    jobs:
      - job: Package
        steps:
          - script: |
              echo "Artifacts would be packaged here"
            displayName: "Mock Package"

  - stage: DeployToDev
    jobs:
      - job: DevDeploy
        steps:
          - script: |
              echo "Deployed backend & frontend to Dev Env"
            displayName: "Mock Deploy to Dev"

  - stage: DeployToQAT
    jobs:
      - job: QATDeploy
        steps:
          - script: |
              echo "Mock Deploy to QAT Env"
            displayName: "Mock Deploy to QAT"

  - stage: DeployToStaging
    jobs:
      - job: Staging
        steps:
          - script: |
              echo "Mock Deploy to Staging"
            displayName: "Mock Deploy to Staging"

  - stage: DeployToProd
    jobs:
      - job: Prod
        steps:
          - script: |
              echo "Mock Deploy to Production"
            displayName: "Mock Deploy to Prod"
